name: Deploy

on:
  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Tag of the image to deploy'
        required: true
        default: 'latest'

env:
  REGISTRY: ghcr.io

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy application
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
            if [ "$(docker ps -aq -f name=kniffel)" ]; then
              docker stop kniffel
              docker rm kniffel
            fi
          
            echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ${{ env.REGISTRY }} --password-stdin
          
            docker pull ghcr.io/likeajohny/kniffel:${{ github.event.inputs.image-tag }}
          
            docker run -d --name kniffel -p 3000:3000 \
              -e PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }} \
              -e PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }} \
              ghcr.io/likeajohny/kniffel:${{ github.event.inputs.image-tag }}
          
            docker logout ${{ env.REGISTRY }}
          EOF
