name: Publish Image

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  tag-image:
    name: Tag Image
    uses: ./.github/workflows/tag.yml
    secrets: inherit

  publish:
    name: Publish Image
    needs:
      - tag-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          echo ${{ secrets.GHCR_PAT }} | docker login -u ${{ github.actor }} ${{ env.REGISTRY }}
      - name: Publish
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/likeajohny/kniffel:${{ needs.tag-image.outputs.image-tag }}
        run: |
          docker build . \
            --build-arg PUBLIC_SUPABASE_URL=${{ secrets.PUBLIC_SUPABASE_URL }} \
            --build-arg PUBLIC_SUPABASE_ANON_KEY=${{ secrets.PUBLIC_SUPABASE_ANON_KEY }} \
            --build-arg ORIGIN=${{ PRODUCTION_DOMAIN }} \
            -t ${{ env.REGISTRY }}/likeajohny/kniffel:${{ needs.tag-image.outputs.image-tag }}
          docker push ${{ env.IMAGE_NAME }}
          
