name: Publish Image

on:
  workflow_dispatch:
  push:

env:
  REGISTRY: ghcr.io

jobs:
  tag-image:
    name: Tag Image
    uses: ./.github/workflows/tag.yml
    secrets: inherit

  publish:
    name: Publish Image
    needs:
      - tag-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login
        run: |
          - docker login -u ${{ github.actor }} -p ${{ secrets.GHCR_PAT }} ${{ env.REGISTRY }}
      - name: Publish
        env:
          IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.actor }}/kniffel:${{ needs.tag-image.outputs.image-tag }}
        run: |
          docker build . -t ${{ env.IMAGE_NAME }}
          docker push ${{ env.IMAGE_NAME }}
          
